import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Link from 'next/link';
const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className='bg-slate-100'>
          <Link
            className='p-2 text-lg font-semibold hover:underline transition-all hover:text-indigo-600 duration-100'
            href={'/'}
          >
            Go to Home page
          </Link>
        </div>
        <main className='p-4 bg-slate-100 min-h-screen'>{children}</main>
      </body>
    </html>
  );
}
